// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Domain;

[Table("trEmployee")]
public partial class Employee
{
    [Key]
    [Column("EmpID")]
    public long EmpId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string EmpName { get; set; }

    [Column("NIK")]
    [StringLength(25)]
    [Unicode(false)]
    public string Nik { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string EmpAddress { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string JobTitle { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Manager { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string Branch { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string PhoneNo { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string TelpNo { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Email { get; set; }

    [Column("KTP")]
    [StringLength(50)]
    [Unicode(false)]
    public string Ktp { get; set; }

    [Column("NPWP")]
    [StringLength(50)]
    [Unicode(false)]
    public string Npwp { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string BankBranch { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string BankAccountName { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? BankAccountNo { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string DocumentFile { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string CreateBy { get; set; }

    [Column("CreateDT", TypeName = "datetime")]
    public DateTime CreateDt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateBy { get; set; }

    [Column("UpdateDT", TypeName = "datetime")]
    public DateTime? UpdateDt { get; set; }

    public bool IsDeleted { get; set; }
}