// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Domain;

[Table("trProductItem")]
public partial class ProductItem
{
    [Key]
    [Column("ProductID")]
    public long ProductId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string ProductCode { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string ProductName { get; set; }

    [Column("ProductCategoryID")]
    public int ProductCategoryId { get; set; }

    [Unicode(false)]
    public string Description { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? Weight { get; set; }

    [Column("DimensionLWH")]
    [StringLength(25)]
    [Unicode(false)]
    public string DimensionLwh { get; set; }

    public int? Status { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string DocumentFile { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string CreateBy { get; set; }

    [Column("CreateDT", TypeName = "datetime")]
    public DateTime CreateDt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateBy { get; set; }

    [Column("UpdateDT", TypeName = "datetime")]
    public DateTime? UpdateDt { get; set; }

    public bool IsDeleted { get; set; }
}