// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Domain;

[Table("trSupplier")]
public partial class Supplier
{
    [Key]
    [Column("SupplierID")]
    public long SupplierId { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string SupplierNo { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string SupplierName { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Address { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string PhoneNo { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Remark { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ApproveBy { get; set; }

    [Column("ApproveDT", TypeName = "datetime")]
    public DateTime? ApproveDt { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string CreateBy { get; set; }

    [Column("CreateDT", TypeName = "datetime")]
    public DateTime CreateDt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateBy { get; set; }

    [Column("UpdateDT", TypeName = "datetime")]
    public DateTime? UpdateDt { get; set; }

    public bool IsDeleted { get; set; }
}