// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Domain;

[Table("tuRoleAccess")]
public partial class RoleAccess
{
    [Key]
    [Column("RoleAccessID")]
    public int RoleAccessId { get; set; }

    [Column("RoleID")]
    public int? RoleId { get; set; }

    public bool? Cr { get; set; }

    public bool? Rd { get; set; }

    public bool? Upd { get; set; }

    public bool? Del { get; set; }

    public bool? App { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string CreateBy { get; set; }

    [Column("CreateDT", TypeName = "datetime")]
    public DateTime CreateDt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateBy { get; set; }

    [Column("UpdateDT", TypeName = "datetime")]
    public DateTime? UpdateDt { get; set; }

    public bool IsDeleted { get; set; }
}