// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Domain;

[Table("td_Invoice")]
public partial class Invoice
{
    [Key]
    [Column("InvoiceID")]
    public long InvoiceId { get; set; }

    [Required]
    [StringLength(25)]
    [Unicode(false)]
    public string InvoiceNo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime TransDate { get; set; }

    [Column("OrderID")]
    public long OrderId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? PaidDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LoanNo { get; set; }

    [Column("WarehouseID")]
    public int WarehouseId { get; set; }

    [Column("BuyerID")]
    public long BuyerId { get; set; }

    [Column("PaymentMethodID")]
    public int? PaymentMethodId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string RequestBy { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal? TotalAmount { get; set; }

    public int? Status { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string DocumentFile { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string CreateBy { get; set; }

    [Column("CreateDT", TypeName = "datetime")]
    public DateTime CreateDt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateBy { get; set; }

    [Column("UpdateDT", TypeName = "datetime")]
    public DateTime? UpdateDt { get; set; }

    public bool IsDeleted { get; set; }
}