// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Domain;

[Table("td_ProductPriceRequest")]
public partial class ProductPriceRequest
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string PriceRequestNo { get; set; }

    [Column("ProductIn_ID")]
    public int ProductInId { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string ProductName { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ProductCode { get; set; }

    [Column("ProductCode_External")]
    [StringLength(50)]
    [Unicode(false)]
    public string ProductCodeExternal { get; set; }

    [StringLength(25)]
    [Unicode(false)]
    public string ProductCategory { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string UnitType { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal Price { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Remark { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ApproveBy { get; set; }

    [Column("ApproveDT", TypeName = "datetime")]
    public DateTime? ApproveDt { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string CreateBy { get; set; }

    [Column("CreateDT", TypeName = "datetime")]
    public DateTime CreateDt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateBy { get; set; }

    [Column("UpdateDT", TypeName = "datetime")]
    public DateTime? UpdateDt { get; set; }

    public bool IsDeleted { get; set; }
}