// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities.Domain;

[Table("td_SalesOrderDetail")]
public partial class SalesOrderDetail
{
    [Key]
    [Column("OrderDetailID")]
    public long OrderDetailId { get; set; }

    [Column("OrderHeaderID")]
    public int OrderHeaderId { get; set; }

    [Column("ProductIn_ID")]
    public int ProductInId { get; set; }

    public long Qty { get; set; }

    [Column("UnitID")]
    public int UnitId { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal Price { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string CreateBy { get; set; }

    [Column("CreateDT", TypeName = "datetime")]
    public DateTime CreateDt { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdateBy { get; set; }

    [Column("UpdateDT", TypeName = "datetime")]
    public DateTime? UpdateDt { get; set; }

    public bool IsDeleted { get; set; }
}